version: '3'

services:

  react:
    container_name: react
    build:
      context: react/
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
    ports:
      - 80:80
    depends_on:
      - server
      
  server:
    container_name: server
    build:
      context: server/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - 3008:3008
    expose:
      - 3008
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:5.7
    container_name: dbmysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/:rw

volumes:
  my-db:

